version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: payment_base_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - payment_gateway_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: payment_base_kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: payment_base_zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://payment_base_kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    volumes:
      - ./fixtures/:/home/appuser/
    networks:
      - payment_gateway_network
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092 || exit -1"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    container_name: payment_base_kafka-topics-generator
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=payment_base_kafka:9092 && 
        kafka-topics --create --topic=transactions_result --if-not-exists --bootstrap-server=payment_base_kafka:9092"
    networks:
      - payment_gateway_network
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    container_name: payment_base_control_center
    hostname: control_center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'payment_base_kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    networks:
      - payment_gateway_network

  prometheus:
    image: prom/prometheus
    container_name: payment_processor_prometheus
    depends_on: 
      - cadvisor
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - payment_gateway_network

  grafana:
    image: grafana/grafana
    container_name: payment_processor_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./metrics/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - payment_gateway_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: payment_processor_cadvisor
    user: root
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - payment_gateway_network

  kafka_exporter:
    image: danielqsj/kafka-exporter
    container_name: payment_processor_kafka_exporter
    environment:
      - KAFKA_SERVERS=payment_base_kafka:9094
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 9308:9308
    networks:
      - payment_gateway_network

  zipkin:
    image: openzipkin/zipkin
    container_name: payment_processor_zipkin
    ports:
      - 9411:9411
    networks:
      - payment_gateway_network
      
networks:
  payment_gateway_network:
    external: true
