prefix       = "gateway"
project_id   = "localdevelopment-392414"
user         = "techlogs.journey@gmail.com"
project_name = "my-project"
region       = "us-east1"
zone         = "us-east1-b"
cluster_name = "my-cluster"
pool_name    = "my-pool"
