version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: payment_gateway_app
    ports:
      - 3001:3001
    volumes:
      - .:/app
    depends_on: 
      postgres:
        condition: service_started
    environment:
      - KAFKA_HOST=payment_base_kafka:9094
      - DB_HOST=payment_gateway_postgres
    networks:
      - payment_gateway_network

  postgres:
    image: postgres:14.7-alpine
    container_name: payment_gateway_postgres
    ports:
      - 5433:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - payment_gateway_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
 

networks:
  payment_gateway_network:
    external: true