version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: payment_processor_app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=payment_base_kafka:9094
      - EXPORTER_ENDPOINT=http://payment_processor_zipkin:9411/api/v2/spans
    volumes:
      - .:/go/src
    networks:
      - payment_gateway_network

networks:
  payment_gateway_network:
    external: true