version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: payment_processor_app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=payment_base_kafka:9094
      - EXPORTER_ENDPOINT=http://payment_processor_zipkin:9411/api/v2/spans
    volumes:
      - .:/go/src
    networks:
      - payment_gateway_network

  postgres:
    image: postgres:14.3-alpine
    container_name: payment_processor_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=transactions
    networks:
      - payment_gateway_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  payment_gateway_network:
    external: true