GET http://localhost:3001/api/v1/accounts

###
GET http://localhost:3001/api/v1/accounts/a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11


###
POST http://localhost:3001/api/v1/accounts
Content-Type: application/json

{
    "name": "conta 3"
}

###
PATCH http://localhost:3001/api/v1/accounts/a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
Content-Type: application/json

{
    "name": "conta 1 alterada",
}