GET http://localhost:3000/api/v1/orders
x-token: ceo0pwvvg0n

###
GET http://localhost:3000/api/v1/orders/11eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
x-token: ceo0pwvvg0n

###
POST http://localhost:3000/api/v1/orders
Content-Type: application/json
x-token: ceo0pwvvg0n

{
    "amount": 1000.33,
    "credit_card_number": "4485460940174065",
    "credit_card_name": "Luiz Carlos",
    "credit_card_expiration_month": 12,
    "credit_card_expiration_year": 2022,
    "credit_card_cvv": "123"
}

###
PATCH http://localhost:3000/api/v1/orders/11eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
Content-Type: application/json

{
    "amount": 1000.33,
    "credit_card_number": "111122222"
}

###
DELETE http://localhost:3000/api/v1/orders/11eebc99-9c0b-4ef8-bb6d-6bb9bd380a11